Creates new Python Package
LD4P/ils-middleware pull request #57
Opened 2021-10-02 19:41 UTC by jermnelson

Fixes #55. 

Adds new `ils_middleware` package that includes `dags` and `tasks` at the same level and uses absolute imports in all source code.

2021-10-02 19:42 UTC, jermnelson commented on Dockerfile
> +COPY --chown=airflow:root dist/ils_middleware-0.1.0-py3-none-any.whl .
I think there should be a better method to install `ils_middleware` in the image. I need to do some more investigation.

2021-10-04 18:01 UTC, jmartin-sul requested changes
noticed what seemed like a small mistaken name change for a parameter, and then another thing that might be an unused variable (or might just be me not understanding an unfamiliar construct)

2021-10-04 20:30 UTC, jermnelson commented on ils_middleware/dags/cornell.py
> +        session_token="{{ task_instance.xcom_pull(key='return_value', task_ids=['folio_login'])[0]}}",
Yes, good catch! Now changed to use `token`.

2021-10-04 20:31 UTC, jermnelson commented on ils_middleware/dags/cornell.py
> +    folio_login = FolioLogin(tenant="cornell", username="", password="")
The `folio_login` task saves the FOLIO JWT to the default `return_value` in inter-tasks communication (XCOM) that is passed to the next task with the `task_ids=['folio_login']` with the call in 56. The default task_id for `FolioLogin` is `folio_login`.

2021-10-04 21:07 UTC, jmartin-sul commented on ils_middleware/dags/cornell.py
> +    folio_login = FolioLogin(tenant="cornell", username="", password="")
sorta/kinda understood that, but either way, convinced that it isn't cruft or an oversight 🙂

2021-10-04 21:13 UTC, jmartin-sul approved these changes

2021-10-04 21:13 UTC, merged